---
# For use with pre-commit.
# See usage instructions at http://pre-commit.com

- id: ansible-doctor
  name: Ansible-doctor
  description: This hook runs ansible-doctor.
  entry: python3 -m ansibledoctor -v --dry-run
  language: python
  # do not pass files to ansible-lint, see:
  # https://github.com/ansible/ansible-lint/issues/611
  pass_filenames: false
  always_run: true
